name: Test GoReleaser Action Integration

on:
  workflow_dispatch:

jobs:
  test-goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Debug GoReleaser Action with Boolean Parameters
        uses: ./
        with:
          step: goreleaser-test
          action-ref: goreleaser/goreleaser-action@v5
          # Explicitly set install-only to true
          install-only: true
          # Additional parameters
          args: "--version"
        env:
          GITHUB_TOKEN: ${{ github.token }}