name: Test Action Wrapping

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write # Required for requesting JWT
  contents: read  # Required for actions/checkout

jobs:
  test-action-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci
      
          
      - name: Test Sigstore Archivista (Original Example)
        id: sigstore-attestation
        uses: ./
        with:
          action-ref: "actions/hello-world-javascript-action@main"
          who-to-greet: "SigstoreNoPrefix"
          step: test-sigstore
          attestations: "environment github slsa"
          attestor-slsa-export: "true"
          enable-sigstore: "true"
          enable-archivista: "true"


  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run your action with sigstore and Archivista
        uses: ./ # Replace this with the path to your action if different
        with:
          step: test
          command: echo hello > hello.txt
          enable-sigstore: true
          enable-archivista: true
          attestations: environment git github slsa
          attestor-slsa-export: true