name: Test Composite Action Support

on:
  push:
    branches: [ feature/composite-actions ]
  pull_request:
    branches: [ main ]
    paths:
      - 'index.js'
      - '.github/workflows/test-composite-action.yml'

jobs:
  test-simple-composite:
    name: Test Simple Composite Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      # Step 1: Create local test composite action
      - name: Create test composite action
        run: |
          mkdir -p .github/actions/test-composite
          
          # Create a simple script that our composite action will execute
          cat > .github/actions/test-composite/goodbye.sh << 'EOF'
          #!/bin/bash
          echo "Goodbye from composite action!"
          EOF
          chmod +x .github/actions/test-composite/goodbye.sh
          
          # Create the composite action metadata
          cat > .github/actions/test-composite/action.yml << 'EOF'
          name: 'Test Composite Action'
          description: 'Test composite action for witness-run-action'
          inputs:
            who-to-greet:
              description: 'Who to greet'
              required: true
              default: 'World'
          outputs:
            random-number:
              description: "Random number output"
              value: ${{ steps.random-number-generator.outputs.random-number }}
          runs:
            using: "composite"
            steps:
              - name: Set greeting
                shell: bash
                run: echo "Hello ${{ inputs.who-to-greet }}"
              
              - name: Generate random number
                id: random-number-generator
                shell: bash
                run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
              
              - name: Run goodbye script
                shell: bash
                run: ${{ github.action_path }}/goodbye.sh
          EOF
      
      # Step 2: Build witness-run-action
      - name: Build
        run: npm run build
        
      # Step 3: Run the action with the witness wrapper
      - name: Run with witness wrapper
        id: test-witness
        uses: ./
        with:
          action-ref: ./.github/actions/test-composite
          step: test-composite
          who-to-greet: 'CI Test Runner'
          
      # Step 4: Verify the outputs and artifacts
      - name: Verify outputs
        run: |
          # Check that a GitOID was generated
          if [[ -z "${{ steps.test-witness.outputs.git_oid }}" ]]; then
            echo "ERROR: GitOID was not generated"
            exit 1
          else
            echo "SUCCESS: GitOID was generated: ${{ steps.test-witness.outputs.git_oid }}"
          fi
          
          # Verify the step summary was created
          if [[ ! -f "$GITHUB_STEP_SUMMARY" ]]; then
            echo "ERROR: Step summary file not found"
            exit 1
          else
            echo "SUCCESS: Step summary file exists"
            cat $GITHUB_STEP_SUMMARY
          fi